AWSTemplateFormatVersion: '2010-09-09'
Description: 'App Runner Service and CloudFront for Coinbase Holdings API'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, uat, prod]
    Description: Environment name

  BaseStackName:
    Type: String
    Default: coinbase-base-dev
    Description: Name of the base infrastructure stack

  GitHubRepo:
    Type: String
    Default: "https://github.com/your-username/iqana_coinbase_backend"
    Description: GitHub repository URL (replace with your actual repo)

  GitHubBranch:
    Type: String
    Default: "main"
    Description: GitHub branch to deploy

Resources:
  # App Runner Service with GitHub source
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub "coinbase-service-${Environment}"
      SourceConfiguration:
        CodeRepository:
          RepositoryUrl: !Ref GitHubRepo
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref GitHubBranch
          CodeConfiguration:
            ConfigurationSource: CONFIGURATION_FILE
        AutoDeploymentsEnabled: false
      InstanceConfiguration:
        Cpu: 0.25 vCPU
        Memory: 0.5 GB
        InstanceRoleArn: !ImportValue
          Fn::Sub: "${BaseStackName}-InstanceRole"
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt AppRunnerService.ServiceUrl
            Id: AppRunnerOrigin
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: AppRunnerOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          Compress: true
        WebACLId: !ImportValue
          Fn::Sub: "${BaseStackName}-WebACLId"
        Enabled: true
        Comment: !Sub "CloudFront distribution for coinbase-service-${Environment}"
        PriceClass: PriceClass_100

Outputs:
  AppRunnerServiceUrl:
    Description: App Runner Service URL (Direct access)
    Value: !Sub "https://${AppRunnerService.ServiceUrl}"
    Export:
      Name: !Sub "${AWS::StackName}-AppRunnerUrl"

  CloudFrontURL:
    Description: CloudFront Distribution URL (Use this for API access - protected)
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontUrl"
