AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base infrastructure for Coinbase Holdings API - ECR, IAM, WAF, CloudFront'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, uat, prod]
    Description: Environment name

Resources:
  # ECR Access Role for App Runner (this is the correct one)
  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "coinbase-apprunner-ecr-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # Instance Role for Secrets Manager access
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "coinbase-apprunner-instance-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:coinbase_api_key_secret*"

  # ECR Repository for Docker images
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: coinbase-service
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # WAF Web ACL for protection
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "coinbase-waf-${Environment}"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "WebACL-${Environment}"
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "RateLimit-${Environment}"
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "CommonRuleSet-${Environment}"
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "IpReputation-${Environment}"

  # CloudWatch Log Group for App Runner logs
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apprunner/coinbase-service-${Environment}"
      RetentionInDays: 7

Outputs:
  ECRRepositoryURI:
    Description: ECR Repository URI for Docker images
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/coinbase-service"
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepo"

  AppRunnerECRAccessRoleArn:
    Description: App Runner ECR Access Role ARN
    Value: !GetAtt AppRunnerECRAccessRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECRAccessRole"

  AppRunnerInstanceRoleArn:
    Description: App Runner Instance Role ARN
    Value: !GetAtt AppRunnerInstanceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-InstanceRole"

  WebACLId:
    Description: WAF Web ACL ID
    Value: !Ref WebACL
    Export:
      Name: !Sub "${AWS::StackName}-WebACLId"

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${AWS::StackName}-LogGroup"
